### PR TITLE
Use print() function for python 2/3 compatibility

### PR DESCRIPTION
**Pull request by phdru**
Also remove trailing spaces.

### CODE REVIEW

**Comment by delitescere** [comment]
👍

**Comment by Samwalton9** [comment]
This is still an issue, apparently stopping me from installing oursql via pip - can the PR be merged please? :D

**Comment by Samwalton9** [comment]
@phdru This doesn't seem to be solved, why was it closed?

**Comment by phdru** [comment]
Support for Python 3 is in branch `py3k`. And the repository anyway seems to be abandoned.

PS. Meanwhile I updated [my fork](https://github.com/sqlobject/oursql) and applied PR #6 and #11 to both `master` and `py3k`.

**Pull request closed without merging**
